name: Win32

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: windows-2019

    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: choco install re2c

    - name: Build ninja
      shell: bash
      run: |
        cmake -Bbuild -A Win32 -T v141_xp 
        cmake --build build --parallel --config Debug
        cmake --build build --parallel --config Release

    - name: Test ninja (Debug)
      run: .\ninja_test.exe
      working-directory: build/Debug

    - name: Test ninja (Release)
      run: .\ninja_test.exe
      working-directory: build/Release

    - name: Create ninja archive
      shell: bash
      run: |
        mkdir artifact
        7z a artifact/ninja-win32.zip ./build/Release/ninja.exe


    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifact/ninja-win32.zip
        asset_name: ninja-win32.zip
        asset_content_type: application/zip
